// Generated by scripts/generate-tokens.mjs from tokens.json. Do not edit by hand:
// change tokens.json and run `npm run tokens`. tokens.test.ts fails when this file is stale (R11.2).

export const tokens = {
	color: {
		bg_void: [0.0667, 0.0706, 0.0784, 1],
		bg_base: [0.102, 0.1098, 0.1176, 1],
		bg_inset: [0.1294, 0.1412, 0.1529, 1],
		bg_panel: [0.149, 0.1608, 0.1725, 1],
		bg_panel_raised: [0.1882, 0.2039, 0.2275, 1],
		bg_hover: [1, 1, 1, 0.045],
		bg_active: [0.9373, 0.8235, 0.3529, 0.1],
		bg_pressed: [0, 0, 0, 0.16],
		line_hairline: [0.9137, 0.8941, 0.8392, 0.1],
		line_edge: [0.9137, 0.8941, 0.8392, 0.2],
		line_strong: [0.9137, 0.8941, 0.8392, 0.36],
		accent: [0.9373, 0.8235, 0.3529, 1],
		accent_bright: [0.9608, 0.8863, 0.5804, 1],
		accent_dim: [0.2902, 0.2275, 0.0706, 1],
		accent_contrast: [0.0667, 0.0706, 0.0784, 1],
		accent_glow: [0.9373, 0.8235, 0.3529, 0.45],
		data: [0.5176, 0.6078, 0.9608, 1],
		data_bright: [0.6863, 0.7451, 0.9765, 1],
		data_dim: [0.1804, 0.2039, 0.298, 1],
		data_glow: [0.5176, 0.6078, 0.9608, 0.45],
		text_bright: [1, 1, 1, 1],
		text: [0.9137, 0.8941, 0.8392, 1],
		text_dim: [0.6392, 0.6196, 0.5725, 1],
		text_faint: [0.4353, 0.4196, 0.3882, 1],
		text_disabled: [0.3333, 0.3216, 0.298, 1],
		status_ok: [0.3373, 0.8235, 0.6196, 1],
		status_warn: [0.9373, 0.8235, 0.3529, 1], // = color.accent
		status_crit: [0.9412, 0.4588, 0.702, 1],
		status_info: [0.5176, 0.6078, 0.9608, 1], // = color.data
		scrim: [0, 0, 0, 0.72],
		shadow: [0, 0, 0, 0.5],
		shadow_strong: [0, 0, 0, 0.8],
	},
	space: {
		space_0_5: 2,
		space_1: 4,
		space_1_5: 6,
		space_2: 8,
		space_3: 12,
		space_4: 16,
		space_5: 20,
		space_6: 24,
		space_8: 32,
		space_10: 40,
		space_12: 48,
		space_16: 64,
		space_20: 80,
		space_24: 96,
		scroll_step: 40,
	},
	radius: {
		r_0: 0,
		r_xs: 1,
		r_sm: 2,
		r_md: 4,
		r_lg: 8,
		r_xl: 14,
		r_pill: 999,
		radius_ui: 2, // = radius.r_sm
		radius_panel: 2, // = radius.r_sm
	},
	borderWidth: {
		bw_hair: 1,
		bw: 1,
		bw_thick: 2,
	},
	fontSize: {
		fs_xs: 11,
		fs_sm: 12,
		fs_base: 13,
		fs_md: 15,
		fs_lg: 18,
		fs_xl: 22,
		fs_2xl: 28,
		fs_3xl: 38,
		fs_4xl: 52,
		fs_5xl: 72,
	},
	lineHeight: {
		lh_tight: 1.1,
		lh: 1.4,
		lh_loose: 1.6,
	},
	letterSpacing: {
		ls_tight: -0.01,
		ls: 0,
		ls_wide: 0.08,
		ls_wider: 0.16,
		ls_widest: 0.3,
	},
	motion: {
		dur_fast: 120,
		dur: 200,
		dur_slow: 360,
		dur_tooltip_hide: 80,
		ease_standard: [0.4, 0, 0.2, 1],
		ease_emphasized: [0.16, 1, 0.3, 1],
	},
	layer: {
		z_base: 'base',
		z_raised: 'raised',
		z_overlay: 'overlay',
		z_modal: 'modal',
		z_popup: 'popup',
		z_toast: 'toast',
		z_tooltip: 'tooltip',
		z_drag: 'drag',
		z_transition: 'transition',
	},
	elevation: {
		shadow_raised: {
			color: [0, 0, 0, 0.5],
			blur: 14,
			spread: 0,
			offset: [0, 6],
		},
		shadow_pop: {
			color: [0, 0, 0, 0.8],
			blur: 24,
			spread: 0,
			offset: [0, 12],
		},
		shadow_inset: {
			color: [0, 0, 0, 0.5],
			blur: 4,
			spread: 0,
			offset: [0, 1],
			inset: true,
		},
		glow_accent: {
			color: [0.9373, 0.8235, 0.3529, 0.45],
			blur: 16,
			spread: 2,
			offset: [0, 0],
		},
		glow_data: {
			color: [0.5176, 0.6078, 0.9608, 0.45],
			blur: 16,
			spread: 2,
			offset: [0, 0],
		},
		text_shadow: {
			color: [0, 0, 0, 1],
			blur: 1,
			spread: 0,
			offset: [0, 1],
		},
	},
	typography: {
		weight_normal: 400,
		weight_semibold: 600,
		weight_bold: 700,
		title_weight: 600, // = typography.weight_semibold
		role_display: {
			family: 'Barlow Condensed',
			weights: [600],
			titleTransform: 'uppercase',
			titleLetterSpacing: 0.08,
		},
		role_body: {
			family: 'Open Sans',
			weights: [400],
			boldRole: 'display',
			size: 13,
			lineHeight: 1.4,
		},
		role_mono: {
			family: 'JetBrains Mono',
			weights: [400],
			transform: 'uppercase',
			letterSpacing: 0.16,
		},
	},
	control: {
		control_h_sm: 26,
		control_h_md: 34,
		control_h_lg: 46,
		control_fs_sm: 13, // = fontSize.fs_base
		control_fs_md: 15, // = fontSize.fs_md
		control_fs_lg: 18, // = fontSize.fs_lg
		icon_sm: 14,
		icon_md: 16,
		icon_lg: 20,
		inset_field: 12, // = space.space_3
		inset_row: 8, // = space.space_2
		focus_ring_width: 1,
		focus_ring_offset: 2,
		press_offset: 1,
		drag_threshold_mouse: 4,
		drag_threshold_touch: 10,
		tooltip_delay: 500,
		hover_move_tolerance: 4,
		tone_auto_crit: 0.25,
		tone_auto_warn: 0.5,
	},
} as const;

export type Tokens = typeof tokens;

export type ColorToken = keyof Tokens['color'];
export type SpaceToken = keyof Tokens['space'];
export type RadiusToken = keyof Tokens['radius'];
export type BorderWidthToken = keyof Tokens['borderWidth'];
export type FontSizeToken = keyof Tokens['fontSize'];
export type LineHeightToken = keyof Tokens['lineHeight'];
export type LetterSpacingToken = keyof Tokens['letterSpacing'];
export type MotionToken = keyof Tokens['motion'];
export type LayerToken = keyof Tokens['layer'];
export type ElevationToken = keyof Tokens['elevation'];
export type TypographyToken = keyof Tokens['typography'];
export type ControlToken = keyof Tokens['control'];
