// Generated by scripts/generate-icons.mjs from src/assets/fonts/icons.txt. Do not edit.

/** Each icon in the icon atlas by name, and the code point `drawText` draws it with (R12.6). */
export const ICON_CODE_POINTS = {
	arrow_back: 0xE5C4,
	build: 0xE869,
	local_gas_station: 0xE546,
	settings: 0xE8B8,
	shield: 0xE9E0,
} as const;

export type IconName = keyof typeof ICON_CODE_POINTS;
