/** One credited thing: a name and the lines under it. */
export interface CreditEntry {
	name: string;
	lines: readonly string[];
	/** For a bundled asset, its directory under `src/assets/fonts/`, which ships its licence. */
	asset?: string;
}

export interface CreditSection {
	heading: string;
	entries: readonly CreditEntry[];
}

/**
 * What the credits screen lists, all of it from the repository: the licence
 * in `LICENSE`, the commit authors in the git history, and the bundled
 * typefaces and icons with the copyright lines and licences their own files
 * carry (`src/assets/fonts/README.md`). A bundled asset added without an
 * entry here fails `credits.test.ts`.
 */
export const CREDITS: readonly CreditSection[] = [
	{
		heading: 'Dual Deckbuilder',
		entries: [
			{
				name: 'A roguelike deckbuilder of vehicular combat',
				lines: ['Released under the PolyForm Noncommercial License 1.0.0.'],
			},
		],
	},
	{
		heading: 'Development',
		entries: [
			{ name: 'Kevin Jonson', lines: [] },
			{ name: 'Alan Hudson', lines: [] },
		],
	},
	{
		heading: 'Typefaces',
		entries: [
			{
				name: 'Barlow Condensed',
				lines: ['Copyright 2017 The Barlow Project Authors', 'SIL Open Font License 1.1'],
				asset: 'barlow-condensed',
			},
			{
				name: 'Open Sans',
				lines: ['Copyright 2020 The Open Sans Project Authors', 'SIL Open Font License 1.1'],
				asset: 'open-sans',
			},
			{
				name: 'JetBrains Mono',
				lines: ['Copyright 2020 The JetBrains Mono Project Authors', 'SIL Open Font License 1.1'],
				asset: 'jetbrains-mono',
			},
		],
	},
	{
		heading: 'Icons',
		entries: [
			{
				name: 'Material Icons',
				lines: ['Google', 'Apache License 2.0'],
				asset: 'material-icons',
			},
		],
	},
	{
		heading: 'Built with',
		entries: [
			{
				name: 'TypeScript, WebGL 2, and Electron',
				lines: ['Font and icon atlases generated by msdf-atlas-gen (Chlumsky)'],
			},
		],
	},
];
