/**
 * R12.6's generated icon set: the names in `src/assets/fonts/icons.txt`,
 * resolved through the icon font's `.codepoints` file, become the committed
 * `src/renderer/engine/text/icons.ts` (name to code point). The build-fonts
 * scripts run this before building the icon atlas and pass the same code
 * points to msdf-atlas-gen, so the module and the atlas cannot disagree.
 * Plain JavaScript with no dependencies, like generate-tokens.mjs.
 *
 *   node scripts/generate-icons.mjs            write icons.ts
 *   node scripts/generate-icons.mjs --check    exit 1 when icons.ts is stale
 *   node scripts/generate-icons.mjs --stdout   print the module instead of writing it
 *   node scripts/generate-icons.mjs --charset  print the msdf-atlas-gen charset
 *   node scripts/generate-icons.mjs --input <file> --stdout
 */
import { readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const iconListPath = resolve(repoRoot, 'src/assets/fonts/icons.txt');
const codePointsPath = resolve(repoRoot, 'src/assets/fonts/material-icons/MaterialIcons-Regular.codepoints');
const outputPath = resolve(repoRoot, 'src/renderer/engine/text/icons.ts');

const ICON_NAME = /^[a-z][a-z0-9_]*$/;

class IconError extends Error {}

/** `name` lines from icons.txt, in file order; blank lines and `#` comments skipped. */
function parseIconList(text) {
	const names = [];
	for (const [index, raw] of text.split(/\r?\n/).entries()) {
		const line = raw.trim();
		if (!line || line.startsWith('#')) continue;
		if (!ICON_NAME.test(line)) throw new IconError(`icons.txt line ${index + 1}: ${JSON.stringify(line)} is not an icon name`);
		if (names.includes(line)) throw new IconError(`icons.txt line ${index + 1}: ${line} is listed twice`);
		names.push(line);
	}
	if (names.length === 0) throw new IconError('icons.txt lists no icons');
	return names;
}

/** The font's `name hex` lines as a map. */
function parseCodePoints(text) {
	const codePoints = new Map();
	for (const raw of text.split(/\r?\n/)) {
		const line = raw.trim();
		if (!line) continue;
		const [name, hex] = line.split(/\s+/);
		// Material Icons lists some names twice (aliases); the first wins.
		if (!codePoints.has(name)) codePoints.set(name, Number.parseInt(hex, 16));
	}
	return codePoints;
}

/** The icon set sorted by name, so the module does not churn when icons.txt is reordered. */
function resolveIcons({ iconList, codePoints }) {
	return parseIconList(iconList)
		.map((name) => {
			const codePoint = codePoints.get(name);
			if (codePoint === undefined) throw new IconError(`${name} is not in the icon font's code point list`);
			return { name, codePoint };
		})
		.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}

function generateModule(icons) {
	const hex = (codePoint) => `0x${codePoint.toString(16).toUpperCase().padStart(4, '0')}`;
	return [
		'// Generated by scripts/generate-icons.mjs from src/assets/fonts/icons.txt. Do not edit.',
		'',
		'/** Each icon in the icon atlas by name, and the code point `drawText` draws it with (R12.6). */',
		'export const ICON_CODE_POINTS = {',
		...icons.map(({ name, codePoint }) => `\t${name}: ${hex(codePoint)},`),
		'} as const;',
		'',
		'export type IconName = keyof typeof ICON_CODE_POINTS;',
		'',
	].join('\n');
}

/** msdf-atlas-gen's charset syntax: hex code points, comma separated. */
function generateCharset(icons) {
	return `${icons.map(({ codePoint }) => `0x${codePoint.toString(16)}`).join(', ')}\n`;
}

function readText(path) {
	try {
		return readFileSync(path, 'utf8');
	} catch (error) {
		throw new IconError(`cannot read ${path}: ${error.message}`);
	}
}

function main(argv) {
	const inputIndex = argv.indexOf('--input');
	const inputPath = inputIndex === -1 ? iconListPath : resolve(argv[inputIndex + 1] ?? '');
	const icons = resolveIcons({ iconList: readText(inputPath), codePoints: parseCodePoints(readText(codePointsPath)) });
	if (argv.includes('--charset')) {
		process.stdout.write(generateCharset(icons));
		return 0;
	}
	const moduleText = generateModule(icons);
	if (argv.includes('--stdout')) {
		process.stdout.write(moduleText);
		return 0;
	}
	if (argv.includes('--check')) {
		let committed = '';
		try {
			committed = readFileSync(outputPath, 'utf8').replace(/\r\n/g, '\n');
		} catch {
			// A missing module is stale by definition.
		}
		if (committed !== moduleText) {
			process.stderr.write('icons.ts is stale: run scripts/build-fonts and commit the result.\n');
			return 1;
		}
		return 0;
	}
	writeFileSync(outputPath, moduleText);
	return 0;
}

/** Node resolves symlinks in `import.meta.url` but not in `argv[1]`, so compare real paths. */
function isMainModule() {
	if (!process.argv[1]) return false;
	try {
		return realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url));
	} catch {
		return false;
	}
}

if (isMainModule()) {
	try {
		process.exitCode = main(process.argv.slice(2));
	} catch (error) {
		if (!(error instanceof IconError)) throw error;
		process.stderr.write(`generate-icons: ${error.message}\n`);
		process.exitCode = 2;
	}
}
